### ISSUE TITLE
PM-1528

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1642]
PM-1528

**Comment by mayani** [comment]
**Author:** @rafaelfsilva

Current version of the R API generates basic workflow in YAML format:


```

pegasus: "5.0"
name: diamond
x-pegasus:
  createdBy: "rafsilva"
  createdOn: "2020-09-03 21:55:29"
  apiLang: "R"
metadata:
  name: "diamond"
  createdby: "Rafael Ferreira da Silva"
jobs:
- type: "job"
  name: "process"
  id: "ID0000001"
  arguments:
  - "-a"
  - "preprocess"
  - "-T"
  - "3"
  - "-i"
  - "f.a"
  - "-o"
  - "f.b1"
  - "f.b2"
  uses:
  - lfn: "f.a"
    type: "input"
  - lfn: "f.b1"
    type: "output"
    stageOut: "true"
    registerReplica: ""
  - lfn: "f.b2"
    type: "output"
    stageOut: "true"
    registerReplica: ""
- type: "job"
  name: "frange"
  id: "ID0000002"
  arguments:
  - "-a"
  - "findrange"
  - "-T"
  - "3"
  - "-i"
  - "f.b1"
  - "-o"
  - "f.c1"
  uses:
  - lfn: "f.b1"
    type: "input"
  - lfn: "f.c1"
    type: "output"
    stageOut: "true"
    registerReplica: ""
- type: "job"
  name: "frange"
  id: "ID0000003"
  arguments:
  - "-a"
  - "findrange"
  - "-T"
  - "3"
  - "-i"
  - "f.b2"
  - "-o"
  - "f.c2"
  uses:
  - lfn: "f.b2"
    type: "input"
  - lfn: "f.c2"
    type: "output"
    stageOut: "true"
    registerReplica: ""
- type: "job"
  name: "analyze"
  id: "ID0000004"
  arguments:
  - "-a"
  - "analyze"
  - "-T"
  - "3"
  - "-i"
  - "f.c1"
  - "f.c2"
  - "-o"
  - "f.d"
  uses:
  - lfn: "f.c1"
    type: "input"
  - lfn: "f.c2"
    type: "input"
  - lfn: "f.d"
    type: "output"
    stageOut: "true"
    registerReplica: ""
jobDependencies:
- id: "ID0000001"
  children:
  - "ID0000002"
  - "ID0000003"
- id: "ID0000002"
  children:
  - "ID0000004"
- id: "ID0000003"
  children:
  - "ID0000004"

```
