### ISSUE TITLE
[PM-1879] Per job symlinking

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1992]
The second is the pegasus.transfer.links option. Currently this is only defined at the Properties scope (ie for a whole workflow). But sometimes we want to decide whether to copy/symlink an input based on the job. E.g. a job that needs to read a small amount of data from a large file - better to symlink. Job that repeatedly reads medium sized file - better to copy. Can the scope of this be extended to at least the SiteCatalog, but perhaps to the workflow/transformation catalog as well

**Reporter:** @spxiwh
**Resolution:** Fixed
**Watchers:**
@duncan-brown
@rynge
@spxiwh
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

@spxiwh if we add it as a profile to the workflow, then it overrides the values.  so want to be clear on semantics between the property and the profile

pegasus.transfer.links is a property that defaults to off. 

so the way to work would be to have a pegasus profile nosymlink. 

so you set 
pegasus.transfer.links to turn on symlinking 
and then set profiles for jobs that don't need symlink. 
this behavior would ensure backward compatibility

let me know if that works for you

**Comment by mayani** [comment]
**Author:** @spxiwh

Hi @vahi. Thanks for considering this. We would be happy with having:

pegasus.transfer.links=true in our pegasus property file.

and a new pegasus.XXX.nosymlink *profile* to override this for individual jobs. Could this profile be set in the site catalog *or* as a property of individual jobs?

Thanks!

**Comment by mayani** [comment]
**Author:** @vahi

@spxiwh5.0.3 dev has this feature now https://pegasus.isi.edu/docs/5.0.3dev/user-guide/data-transfers.html#symlinking-against-input-data you can use pegasus profile nosymlink to turn off symlinking for jobs. please give it a try

**Comment by mayani** [comment]
**Author:** @vahi

this is resolved and unit tests are also added for the planner's modules.

**Comment by mayani** [comment]
**Author:** @spxiwh

@vahi Great, thanks! Apologies for not replying to this sooner, for some reason I cannot persuade JIRA to send me email notifications when there's new responses. I'll test this by the end of the week (with 1883 as well), and then, assuming there's no issues, I'll be very keen to have a new release :-).

**Comment by mayani** [comment]
**Author:** @spxiwh

@vahi Unfortunately, I don't seem to be able to get this to work! I have the new setting set in the site catalog (where I want it to be):

```
- name: condorpool_copy
  arch: x86_64
  os.type: linux
  directories: []
  profiles:
    condor:
      request_memory: '1000'
      request_disk: '1000'
      accounting_group: ligo.prod.o3.cbc.bbh.pycbcoffline
      +OpenScienceGrid: 'False'
      should_transfer_files: 'Yes'
      when_to_transfer_output: ON_EXIT_OR_EVICT
      getenv: 'True'
      +DESIRED_Sites: '"nogrid"'
      +IS_GLIDEIN: '"False"'
      +flock_local: 'True'
    pegasus:
      style: condor
      data.configuration: nonsharedfs
      transfer.bypass.input.staging: 'true'
      nosymlink: 'True'
      auxillary.local: 'true'
    dagman:
      retry: '2'
```

and also tried adding this to the abstract workflow:

```
  profiles:
    selector:
      execution_site: condorpool_copy
    dagman:
      category: coinc
    pegasus:
      nosymlink: 1
```

But whatever I do I still see:

```
pegasus-transfer --threads 1  --symlink  1>&2 << 'eof'
[
 { "type": "transfer",
   "linkage": "input",
   "lfn": "H1L1V1-BANK2HDF-1186740100-3400.hdf",
   "id": 1,
   "src_urls": [
     { "site_label": "local", "url": "file:///home/ian.harry/lscsoft_git/src/pycbc/examples/search/output/local-site-scratch/work/./gw-main.dax_gw-main/./H1L1V1-BANK2HDF-1186740100-3400.hdf", "checkpoint": "false" }
   ],
```

In the input files. Am I doing something wrong here? The workflow is here on the LIGO Caltech cluster:

```
/home/ian.harry/lscsoft_git/src/pycbc/examples/search/output
```
