### ISSUE TITLE
[PM-1889] Escape command line args passed to Job

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#2002]
Currently, when we invoke job.add_args("1 2") it is written to the YAML file as below, but the same is written to the .sh file as 1 2 instead of '1 2'.

```yml
- type: job
  name: ls
  arguments:
  - 1 2
  - 3 4
```

```sh
pegasus-kickstart  -n ls -N ID0000001 -o listing.txt -R condorpool  -s listing.txt=listing.txt -L .. /bin/ls 1 2 3 4
```

When writing the arguments into the .sh file, they should be shell escaped.

**Reporter:** @mayani
**Watchers:**
@papajim
@mayani
@vahi
