### ISSUE TITLE
when parsing container mount points in the TC, normalize the path to ensure any duplicate / in directory paths are removed

### ISSUE THREAD

**Issue by vahi** [pegasus-isi/pegasus#2103]
**Describe the bug**
This got encountered when adding a new end to end workflow test for workflow with docker containers, and symlinking of raw inputs enabled. 

If test was invoked, as 
./run-bamboo-test inside/nonsharedfs-symlink/

the test generated the container description as below

``` yaml
containers:
- name: centos-osgvo-el8
  type: docker
  image: docker:///hub.opensciencegrid.org/opensciencegrid/osgvo-el8:latest
  mounts: ['/scitech/shared/scratch-90-days/5.1.0dev/inside/nonsharedfs-symlink//shared:/existing/data:ro']
  image.site: local
  profiles:
    env: {APP_HOME: /tmp/myscratch, JAVA_HOME: /bin/java.1.8}

```

The above caused the symlinking not to be triggered as a string compare failed in the planner transfer module.
Invoking the same test as 

If test was invoked, as 
./run-bamboo-test inside/nonsharedfs-symlink

the test generated the container description as below

``` yaml
containers:
- name: centos-osgvo-el8
  type: docker
  image: docker:///hub.opensciencegrid.org/opensciencegrid/osgvo-el8:latest
  mounts: ['/scitech/shared/scratch-90-days/5.1.0dev/inside/nonsharedfs-symlink/shared:/existing/data:ro']
  image.site: local
  profiles:
    env: {APP_HOME: /tmp/myscratch, JAVA_HOME: /bin/java.1.8}

```
triggered symlinking correctly. 

The planner parser of the transformation catalog should normalize the mount points when populating it's internal data structures to avoid users tripping over it.

**To Reproduce**
Steps to reproduce the behavior.
1.  Run the end to end workflow test as
./run-bamboo-test inside/nonsharedfs-symlink/

**Expected behavior**
Whether the trailing slash is provided or not should not affect the planners behavior 

**Version Information (please complete the following information):**
 - Pegasus Version 5.1.0dev , 5.0.9

**Submit Directory**
If applicable, attach the submit directory.

**Additional context**
