### ISSUE TITLE
symlinking of data is broken when doing transfers on the HOST OS for containerized jobs

### ISSUE THREAD

**Issue by vahi** [pegasus-isi/pegasus#2104]
**Describe the bug**

when symlinking is enabled on the host OS for a job set to run via a container, then Pegasus setups the wrong urls for symlinking. this applies to both docker and singularity invocations 

In the generated pegasus lite script we see this snippet for the data transfers happening on the HOST OS

```
# stage in data and executables
pegasus-transfer --threads 1  --symlink  1>&2 << 'eof'
[
 { "type": "transfer",
   "linkage": "input",
   "lfn": "pegasus-preprocess-4.0",
   "id": 1,
   "src_urls": [
     { "site_label": "condorpool", "url": "file:///scitech/shared/scratch-90-days/5.1.0dev/044-docker/host/nonsharedfs-symlink/scratch/bamboo/pegasus/blackdiamond/run0001/00/00/pegasus-preprocess-4.0", "checkpoint": "false" }
   ],
   "dest_urls": [
     { "site_label": "condorpool", "url": "file://$PWD/pegasus-preprocess-4.0" }
   ] }
 ,
 { "type": "transfer",
   "linkage": "input",
   "lfn": "f.a",
   "id": 2,
   "src_urls": [
     { "site_label": "condorpool", "url": "file:///existing/data/f.a", "priority": 50, "checkpoint": "false" }
   ],
   "dest_urls": [
     { "site_label": "condorpool", "url": "symlink://$PWD/f.a" }
   ] }
]
```

The container in the transformation  catalog is described as follows

```yaml 
containers:
- name: centos-osgvo-el8
  type: docker
  image: docker:///hub.opensciencegrid.org/opensciencegrid/osgvo-el8:latest
  mounts: ['/scitech/shared/scratch-90-days/5.1.0dev/044-docker/host/nonsharedfs-symlink/shared:/existing/data:ro']
  image.site: local
  profiles:
    env: {APP_HOME: /tmp/myscratch, JAVA_HOME: /bin/java.1.8}

```

**To Reproduce**
Steps to reproduce the behavior.
run the end to end workflow test 044-docker/host/nonsharedfs-symlink/

**Expected behavior**

The generated transfer snippet for symlink job should be that the source URL should be the actual on the HOST OS  i.e. /scitech/shared/scratch-90-days/5.1.0dev/044-docker/host/nonsharedfs-symlink/shared/f.a 

```
# stage in data and executables
pegasus-transfer --threads 1  --symlink  1>&2 << 'eof'
[
 
 { "type": "transfer",
   "linkage": "input",
   "lfn": "f.a",
   "id": 2,
   "src_urls": [
     { "site_label": "condorpool", "url": "file:///scitech/shared/scratch-90-days/5.1.0dev/044-docker/host/nonsharedfs-symlink/shared/f.a", "priority": 50, "checkpoint": "false" }
   ],
   "dest_urls": [
     { "site_label": "condorpool", "url": "symlink://$PWD/f.a" }
   ] }
]
```

And the transformation catalog entry should have the container mount to the same directory inside, instead of mapping to a different dir?

```yaml 
containers:
- name: centos-osgvo-el8
  type: docker
  image: docker:///hub.opensciencegrid.org/opensciencegrid/osgvo-el8:latest
  mounts: ['/scitech/shared/scratch-90-days/5.1.0dev/044-docker/host/nonsharedfs-symlink/shared:/scitech/shared/scratch-90-days/5.1.0dev/044-docker/host/nonsharedfs-symlink/shared:ro']
  image.site: local
  profiles:
    env: {APP_HOME: /tmp/myscratch, JAVA_HOME: /bin/java.1.8}

```

**Version Information (please complete the following information):**
 - applies only to Pegasus 5.1.0dev where we have changed the default of data transfers

**Submit Directory**
If applicable, attach the submit directory.

**Additional context**
